name: Arch Manager CI - INSTALL UPDATE

on:
  push:
    branches: [ master ]

jobs:
  arch-test:
    # Use Ubuntu runner but in an Arch container
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      # Bootstrap pacman keyring (required in a fresh container)
      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      # Install dependencies: Python, Git, SSH, rsync, etc (realistically only python git needed)
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm \
            python \
            git \
            openssh \
            rsync \
            go \
            sudo

      - name: Create slave user
        run: |
          useradd -m slave 
          echo "slave ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/slave

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Give slave ownership of workspace
        run: |
          chown -R slave:slave "$GITHUB_WORKSPACE"

      # Start an SSH agent
      - name: Set up SSH key for slave user
        run: |
          # Create .ssh directory
          mkdir -p /home/slave/.ssh
          chmod 700 /home/slave/.ssh
          
          # Write private key
          echo "${{ secrets.SSH_KEY }}" > /home/slave/.ssh/id_ed25519
          chmod 600 /home/slave/.ssh/id_ed25519
          
          # Add GitHub to known_hosts
          ssh-keyscan github.com >> /home/slave/.ssh/known_hosts
          chown -R slave:slave /home/slave/.ssh

      # Finally, run manager.py
      - name: Run ArchManagerPY as slave
        run: |
          sudo -u slave bash -lc "cd $GITHUB_WORKSPACE && python3 manager.py -iu --no-confirm"
